apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    env: dev
spec:
  replicas: 3
  selector:
    app: nginx-pod
    env: dev
    type: chat
  template:
    metadata:
      name: nginx-pod-rc
      labels:
        app: nginx-pod
        env: dev
    spec:
      containers:
        - name: nginx-rc-pod
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.2"
              memory: "100Mi"
