apiVersion: v1
kind: Pod
metadata:
  name: downward-api-volume-pod
  labels:
     env: test
     app: nginx
spec:
  containers:
    - name: downward-api-nginx-pod
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8989
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html/
        - name: nginx-data
          mountPath: /var/www/html/
  volumes:
    - name: nginx-data
      downwardAPI:
        items:
          - path: index.html
            fieldRef: 
              fieldPath: metadata.name
