apiVersion: v1
kind: Pod
metadata:
  name: downward-api-pod
  labels:
     env: test
     app: nginx
spec:
  containers:
    - name: dawnward-api-alpine-pod
      image: alpine
      command: ['/bin/sh']
      args: ["-c", "while true;do  date >> /mnt/index.html; echo ${PID} >> /mnt/index.html; sleep 10;done"]
      env:
        - name: PID          # environment variable filedRef
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: nginx-data
          mountPath: /mnt/
    - name: downward-api-nginx-pod
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8989
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html/
        - name: nginx-data
          mountPath: /var/www/html/
  volumes:
    - name: nginx-data
      emptyDir: {}
