apiVersion: v1
kind: Pod
metadata:
  name: downward-api-resorce-env
spec:
  containers:
    - name: downward-api-resorce-env-c1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        limits:
          cpu: "200m"
          memory: "300Mi"
        requests:
          cpu: "200m"
          memory: "300Mi"
     
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-data
      downwardAPI:
        items:
          - path: index.html
            resourceFieldRef:
              containerName: downward-api-resorce-env-c1
              resource: limits.memory
      
     
          

