apiVersion: v1
kind: Pod
metadata:
  name: downward-api-resorce-env
spec:
  containers:
    - name: downward-api-resorce-env-c1
      image: nginx
      # command: ["/bin/bash"]
      # args: ["-c", "while true;do echo $CUP_LIMIT : $MEM_LIMIT >> /usr/share/nginx/html/index.html /var/www/html/index.html;sleep 10; done"]
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        limits:
          cpu: "200m"
          memory: "300Mi"
        requests:
          cpu: "200m"
          memory: "300Mi"
      env:
        - name: CUP_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: downward-api-resorce-env-c1
              resource: limits.cpu
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: downward-api-resorce-env-c1
              resource: limits.memory
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-data
      emptyDir: {}
     
          

