apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs-
spec:
  containers:
    - name: nginx-nfs-1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: type-nfs
          mountPath: /var/www/html/
  volumes:
    - name: type-nfs
      nfs:
        server: 192.168.0.224
        path: /nfs
      