apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  capacity
    storage: 5Gi
  accessModes:
    - ReadwriteMany
  nfs:
    server: 192.168.0.221
    path: /nfs
  
      