apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: release, operator: DoesNotExist }
      - {key: env, operator: In, values: ["dev","test"]}
  template:
    metadata: 
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx-deploy-c
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-rs-data
              mountPath: /usr/share/nginx/html
      restartPolicy: Always
      volumes:
        - name: nginx-rs-data
          emptyDir: {}
         
          