apiVersion: v1
kind: Pod
metadata:
  name: nginx-init-container
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: nginx-c
      image: nginx
      ports:
        - name: nginx-port
          containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html/
  initContainers:
    - name: alpine-c
      image: alpine
      command:
        - "wget"
        - "-O"
        - "/var/tmp/index.html"
        - https://github.com/shiva2925/initcontainer/blob/main/index.html?raw=true
      volumeMounts:
        - name: shared-data
          mountPath: /var/tmp
  volumes:
    - name: shared-data
      emptyDir: {}
        