apiVersion: v1
kind: Pod
metadata: 
  name: multi-container
  labels:
    app: nginx
    env: poduction
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh"]
      args: ["-c","while true; do date >> /var/tmp/index.html; sleep 10; done"]
      volumeMounts:
        - name: multi-container-store
          mountPath: /var/tmp/
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          hostPort: 8090
          protocol: TCP

      volumeMounts:
        - name: multi-container-store
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: multi-container-store
      emptyDir: {}
    
