apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
     env: test
     app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
  volumes:
    - name: nginx-data
      emptyDir: {}
