apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv0
spec:
  storageClassName: sts-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 3Gi
  hostPath:
    path: "/mnt/hostpath0"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv1
spec:
  storageClassName: sts-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 3Gi
  hostPath:
    path: "/mnt/hostpath1"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv2
spec:
  storageClassName: sts-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 3Gi
  hostPath:
    path: "/mnt/hostpath2"
    type: DirectoryOrCreate